-- Round 12: structured departments and ranks / roles for profiles and jobs.
-- Keys come from src/features/roles/taxonomy.ts and are validated in the app (zod), not with
-- database enums, so a new rank never needs a migration. The checks below only enforce the
-- snake_case shape and sensible lengths.
-- 1. profiles: department + rank / role, the "Other" text, cadet stage / course, the cadet's
--    target job role, and an occupation text for people without a maritime rank. The old
--    maritime_profiles.rank text stays (history and display fallback).
-- 2. jobs: department, accepted ranks / roles (several), the "Other" text, and the minimum match
--    needed to apply (0..100, 0 = off, default 70; existing rows take the default). The old
--    jobs.rank text stays.
-- 3. Backfill: old rank texts that match a taxonomy label or synonym (the same list
--    normaliseLegacyRank uses, compared case, space and punctuation-insensitively) get keys.
--    Only rows without a key are touched, so re-running changes nothing. Unmapped rows stay null.
-- 4. Existing shore jobs that still have no department after the backfill would be gated only by
--    job-title word overlap, so their minimum match starts at 0 (off) until the recruiter picks a
--    department and accepted roles. Every other job keeps the default 70.
-- Non-destructive: adds columns, check constraints and indexes, fills empty keys; deletes nothing.

alter table public.profiles
  add column if not exists role_department_key text,
  add column if not exists role_key text,
  add column if not exists role_other_text text,
  add column if not exists cadet_stage_key text,
  add column if not exists cadet_course_key text,
  add column if not exists target_department_key text,
  add column if not exists target_role_key text,
  add column if not exists occupation_text text;
-- statement-breakpoint

alter table public.profiles
  drop constraint if exists profiles_structured_role_check;
-- statement-breakpoint

alter table public.profiles
  add constraint profiles_structured_role_check check (
    (role_department_key is null or role_department_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and (role_key is null or role_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and (cadet_stage_key is null or cadet_stage_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and (cadet_course_key is null or cadet_course_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and (target_department_key is null or target_department_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and (target_role_key is null or target_role_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and (role_other_text is null or (role_other_text = btrim(role_other_text) and char_length(role_other_text) between 1 and 100))
    and (occupation_text is null or (occupation_text = btrim(occupation_text) and char_length(occupation_text) between 1 and 120))
  );
-- statement-breakpoint

alter table public.jobs
  add column if not exists department_key text,
  add column if not exists accepted_role_keys text[] not null default '{}'::text[],
  add column if not exists role_other_text text,
  add column if not exists min_match_to_apply smallint not null default 70;
-- statement-breakpoint

alter table public.jobs
  drop constraint if exists jobs_structured_role_check;
-- statement-breakpoint

alter table public.jobs
  add constraint jobs_structured_role_check check (
    (department_key is null or department_key ~ '^[a-z][a-z0-9_]{0,63}$')
    and cardinality(accepted_role_keys) <= 20
    and array_to_string(accepted_role_keys, ',') ~ '^([a-z][a-z0-9_]{0,63}(,[a-z][a-z0-9_]{0,63})*)?$'
    and (role_other_text is null or (role_other_text = btrim(role_other_text) and char_length(role_other_text) between 1 and 100))
    and min_match_to_apply between 0 and 100
  );
-- statement-breakpoint

create index if not exists jobs_department_key_idx
  on public.jobs (department_key)
  where department_key is not null and status = 'published' and deleted_at is null;
-- statement-breakpoint

create index if not exists jobs_accepted_role_keys_idx
  on public.jobs using gin (accepted_role_keys);
-- statement-breakpoint

with role_map(rank_text, role_key, department_key) as (
  values
    ('master captain', 'master', 'deck_officers'),
    ('chief officer', 'chief_officer', 'deck_officers'),
    ('second officer', 'second_officer', 'deck_officers'),
    ('third officer', 'third_officer', 'deck_officers'),
    ('junior officer fourth officer', 'junior_deck_officer', 'deck_officers'),
    ('deck cadet trainee officer', 'deck_cadet', 'deck_officers'),
    ('bosun', 'bosun', 'deck_ratings'),
    ('pumpman', 'pumpman', 'deck_ratings'),
    ('able seaman ab', 'able_seaman', 'deck_ratings'),
    ('able seaman', 'able_seaman', 'deck_ratings'),
    ('ordinary seaman os', 'ordinary_seaman', 'deck_ratings'),
    ('ordinary seaman', 'ordinary_seaman', 'deck_ratings'),
    ('deck trainee', 'deck_trainee', 'deck_ratings'),
    ('chief engineer', 'chief_engineer', 'engine_officers'),
    ('second engineer 2nd engineer', 'second_engineer', 'engine_officers'),
    ('second engineer', 'second_engineer', 'engine_officers'),
    ('third engineer 3rd engineer', 'third_engineer', 'engine_officers'),
    ('third engineer', 'third_engineer', 'engine_officers'),
    ('fourth engineer 4th engineer', 'fourth_engineer', 'engine_officers'),
    ('fourth engineer', 'fourth_engineer', 'engine_officers'),
    ('junior engineer fifth engineer', 'junior_engineer', 'engine_officers'),
    ('engine cadet trainee engineer', 'engine_cadet', 'engine_officers'),
    ('electro technical officer eto', 'eto', 'engine_officers'),
    ('electro technical officer', 'eto', 'engine_officers'),
    ('electrical officer', 'electrical_officer', 'engine_officers'),
    ('gas engineer lng lpg', 'gas_engineer', 'engine_officers'),
    ('gas engineer', 'gas_engineer', 'engine_officers'),
    ('fitter', 'fitter', 'engine_ratings'),
    ('motorman', 'motorman', 'engine_ratings'),
    ('oiler', 'oiler', 'engine_ratings'),
    ('wiper', 'wiper', 'engine_ratings'),
    ('engine trainee', 'engine_trainee', 'engine_ratings'),
    ('electrician electro technical rating', 'electrician', 'engine_ratings'),
    ('chief cook', 'chief_cook', 'catering'),
    ('cook', 'cook', 'catering'),
    ('second cook', 'second_cook', 'catering'),
    ('messman', 'messman', 'catering'),
    ('chief steward', 'chief_steward', 'catering'),
    ('steward', 'steward', 'catering'),
    ('hotel purser staff', 'hotel_purser', 'catering'),
    ('dp operator dpo sdpo', 'dp_operator', 'specialist_offshore'),
    ('dp operator', 'dp_operator', 'specialist_offshore'),
    ('crane operator', 'crane_operator', 'specialist_offshore'),
    ('rov pilot technician', 'rov_pilot', 'specialist_offshore'),
    ('barge master', 'barge_master', 'specialist_offshore'),
    ('offshore installation manager oim', 'oim', 'specialist_offshore'),
    ('offshore installation manager', 'oim', 'specialist_offshore'),
    ('tug master', 'tug_master', 'specialist_offshore'),
    ('yacht captain crew', 'yacht_crew', 'specialist_offshore'),
    ('inland river master', 'inland_master', 'specialist_offshore'),
    ('marine pilot', 'marine_pilot', 'specialist_offshore'),
    ('technical superintendent', 'technical_superintendent', 'technical_fleet'),
    ('marine superintendent', 'marine_superintendent', 'technical_fleet'),
    ('fleet manager', 'fleet_manager', 'technical_fleet'),
    ('technical manager', 'technical_manager', 'technical_fleet'),
    ('electrical superintendent', 'electrical_superintendent', 'technical_fleet'),
    ('new building site superintendent', 'site_superintendent', 'technical_fleet'),
    ('hseq manager', 'hseq_manager', 'hseq_vetting'),
    ('designated person ashore dpa', 'dpa', 'hseq_vetting'),
    ('designated person ashore', 'dpa', 'hseq_vetting'),
    ('company security officer cso', 'cso', 'hseq_vetting'),
    ('company security officer', 'cso', 'hseq_vetting'),
    ('vetting manager inspector', 'vetting_manager', 'hseq_vetting'),
    ('sire cdi inspector', 'sire_inspector', 'hseq_vetting'),
    ('safety officer', 'safety_officer', 'hseq_vetting'),
    ('operations manager', 'operations_manager', 'operations_commercial'),
    ('ship operator', 'ship_operator', 'operations_commercial'),
    ('chartering manager broker', 'chartering_manager', 'operations_commercial'),
    ('commercial manager', 'commercial_manager', 'operations_commercial'),
    ('post fixture claims executive', 'post_fixture', 'operations_commercial'),
    ('bunker trader', 'bunker_trader', 'operations_commercial'),
    ('crewing manager', 'crewing_manager', 'crewing_manning'),
    ('crew coordinator', 'crew_coordinator', 'crewing_manning'),
    ('manning agent', 'manning_agent', 'crewing_manning'),
    ('travel logistics coordinator', 'travel_logistics', 'crewing_manning'),
    ('port captain', 'port_captain', 'port_terminal_logistics'),
    ('harbour master', 'harbour_master', 'port_terminal_logistics'),
    ('terminal manager', 'terminal_manager', 'port_terminal_logistics'),
    ('freight forwarder', 'freight_forwarder', 'port_terminal_logistics'),
    ('customs shipping agent', 'shipping_agent', 'port_terminal_logistics'),
    ('logistics executive', 'logistics_executive', 'port_terminal_logistics'),
    ('marine surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('class surveyor', 'class_surveyor', 'survey_class_legal_insurance'),
    ('marine consultant', 'marine_consultant', 'survey_class_legal_insurance'),
    ('marine lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('p and i insurance executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('average adjuster', 'average_adjuster', 'survey_class_legal_insurance'),
    ('naval architect', 'naval_architect', 'shipyard_engineering'),
    ('shipyard project manager', 'shipyard_project_manager', 'shipyard_engineering'),
    ('marine engineer shore', 'marine_engineer_shore', 'shipyard_engineering'),
    ('marine engineer', 'marine_engineer_shore', 'shipyard_engineering'),
    ('repair manager', 'repair_manager', 'shipyard_engineering'),
    ('director ceo', 'director_ceo', 'management'),
    ('general manager', 'general_manager', 'management'),
    ('department head', 'department_head', 'management'),
    ('recruitment manager', 'recruitment_manager', 'recruitment_hr'),
    ('recruiter talent acquisition', 'recruiter', 'recruitment_hr'),
    ('hr manager', 'hr_manager', 'recruitment_hr'),
    ('hr executive', 'hr_executive', 'recruitment_hr'),
    ('payroll compliance officer', 'payroll_compliance', 'recruitment_hr'),
    ('maritime training institute head principal', 'institute_head', 'training'),
    ('senior faculty lecturer', 'senior_faculty', 'training'),
    ('simulator instructor bridge engine dp', 'simulator_instructor', 'training'),
    ('simulator instructor', 'simulator_instructor', 'training'),
    ('stcw course instructor bst aff medical', 'stcw_instructor', 'training'),
    ('stcw course instructor', 'stcw_instructor', 'training'),
    ('assessor examiner', 'assessor_examiner', 'training'),
    ('online course creator coach', 'online_course_creator', 'training'),
    ('mentor ex seafarer', 'mentor', 'training'),
    ('mentor', 'mentor', 'training'),
    ('soft skills wellbeing trainer', 'wellbeing_trainer', 'training'),
    ('captain', 'master', 'deck_officers'),
    ('master mariner', 'master', 'deck_officers'),
    ('master', 'master', 'deck_officers'),
    ('capt', 'master', 'deck_officers'),
    ('ship master', 'master', 'deck_officers'),
    ('shipmaster', 'master', 'deck_officers'),
    ('chief mate', 'chief_officer', 'deck_officers'),
    ('c o', 'chief_officer', 'deck_officers'),
    ('co', 'chief_officer', 'deck_officers'),
    ('first officer', 'chief_officer', 'deck_officers'),
    ('first mate', 'chief_officer', 'deck_officers'),
    ('chief off', 'chief_officer', 'deck_officers'),
    ('2nd officer', 'second_officer', 'deck_officers'),
    ('2 o', 'second_officer', 'deck_officers'),
    ('2nd mate', 'second_officer', 'deck_officers'),
    ('second mate', 'second_officer', 'deck_officers'),
    ('2nd off', 'second_officer', 'deck_officers'),
    ('3rd officer', 'third_officer', 'deck_officers'),
    ('3 o', 'third_officer', 'deck_officers'),
    ('3rd mate', 'third_officer', 'deck_officers'),
    ('third mate', 'third_officer', 'deck_officers'),
    ('3rd off', 'third_officer', 'deck_officers'),
    ('junior officer', 'junior_deck_officer', 'deck_officers'),
    ('fourth officer', 'junior_deck_officer', 'deck_officers'),
    ('4th officer', 'junior_deck_officer', 'deck_officers'),
    ('4 o', 'junior_deck_officer', 'deck_officers'),
    ('junior deck officer', 'junior_deck_officer', 'deck_officers'),
    ('4th mate', 'junior_deck_officer', 'deck_officers'),
    ('deck cadet', 'deck_cadet', 'deck_officers'),
    ('trainee officer', 'deck_cadet', 'deck_officers'),
    ('trainee navigating officer', 'deck_cadet', 'deck_officers'),
    ('tno', 'deck_cadet', 'deck_officers'),
    ('nautical cadet', 'deck_cadet', 'deck_officers'),
    ('boatswain', 'bosun', 'deck_ratings'),
    ('bos n', 'bosun', 'deck_ratings'),
    ('pump man', 'pumpman', 'deck_ratings'),
    ('ab', 'able_seaman', 'deck_ratings'),
    ('a b', 'able_seaman', 'deck_ratings'),
    ('able seafarer deck', 'able_seaman', 'deck_ratings'),
    ('able bodied seaman', 'able_seaman', 'deck_ratings'),
    ('os', 'ordinary_seaman', 'deck_ratings'),
    ('o s', 'ordinary_seaman', 'deck_ratings'),
    ('trainee seaman', 'deck_trainee', 'deck_ratings'),
    ('deck boy', 'deck_trainee', 'deck_ratings'),
    ('tos', 'deck_trainee', 'deck_ratings'),
    ('trainee os', 'deck_trainee', 'deck_ratings'),
    ('c e', 'chief_engineer', 'engine_officers'),
    ('ce', 'chief_engineer', 'engine_officers'),
    ('chief engg', 'chief_engineer', 'engine_officers'),
    ('chief eng', 'chief_engineer', 'engine_officers'),
    ('chief engineer officer', 'chief_engineer', 'engine_officers'),
    ('2nd engineer', 'second_engineer', 'engine_officers'),
    ('2 e', 'second_engineer', 'engine_officers'),
    ('2nd engg', 'second_engineer', 'engine_officers'),
    ('2nd eng', 'second_engineer', 'engine_officers'),
    ('first engineer', 'second_engineer', 'engine_officers'),
    ('1st engineer', 'second_engineer', 'engine_officers'),
    ('3rd engineer', 'third_engineer', 'engine_officers'),
    ('3 e', 'third_engineer', 'engine_officers'),
    ('3rd engg', 'third_engineer', 'engine_officers'),
    ('3rd eng', 'third_engineer', 'engine_officers'),
    ('4th engineer', 'fourth_engineer', 'engine_officers'),
    ('4 e', 'fourth_engineer', 'engine_officers'),
    ('4th engg', 'fourth_engineer', 'engine_officers'),
    ('4th eng', 'fourth_engineer', 'engine_officers'),
    ('junior engineer', 'junior_engineer', 'engine_officers'),
    ('fifth engineer', 'junior_engineer', 'engine_officers'),
    ('5th engineer', 'junior_engineer', 'engine_officers'),
    ('5 e', 'junior_engineer', 'engine_officers'),
    ('je', 'junior_engineer', 'engine_officers'),
    ('engine cadet', 'engine_cadet', 'engine_officers'),
    ('trainee engineer', 'engine_cadet', 'engine_officers'),
    ('trainee marine engineer', 'engine_cadet', 'engine_officers'),
    ('tme', 'engine_cadet', 'engine_officers'),
    ('eto', 'eto', 'engine_officers'),
    ('electrical engineer', 'eto', 'engine_officers'),
    ('electro officer', 'electrical_officer', 'engine_officers'),
    ('elec officer', 'electrical_officer', 'engine_officers'),
    ('lng engineer', 'gas_engineer', 'engine_officers'),
    ('lpg engineer', 'gas_engineer', 'engine_officers'),
    ('cargo engineer', 'gas_engineer', 'engine_officers'),
    ('engine fitter', 'fitter', 'engine_ratings'),
    ('motor man', 'motorman', 'engine_ratings'),
    ('greaser', 'oiler', 'engine_ratings'),
    ('trainee wiper', 'engine_trainee', 'engine_ratings'),
    ('engine boy', 'engine_trainee', 'engine_ratings'),
    ('electrician', 'electrician', 'engine_ratings'),
    ('electro technical rating', 'electrician', 'engine_ratings'),
    ('etr', 'electrician', 'engine_ratings'),
    ('ch cook', 'chief_cook', 'catering'),
    ('head cook', 'chief_cook', 'catering'),
    ('ship cook', 'cook', 'catering'),
    ('2nd cook', 'second_cook', 'catering'),
    ('assistant cook', 'second_cook', 'catering'),
    ('mess man', 'messman', 'catering'),
    ('mess boy', 'messman', 'catering'),
    ('general steward', 'messman', 'catering'),
    ('gs', 'messman', 'catering'),
    ('ch steward', 'chief_steward', 'catering'),
    ('head steward', 'chief_steward', 'catering'),
    ('stewardess', 'steward', 'catering'),
    ('purser', 'hotel_purser', 'catering'),
    ('hotel manager', 'hotel_purser', 'catering'),
    ('hotel staff', 'hotel_purser', 'catering'),
    ('purser staff', 'hotel_purser', 'catering'),
    ('dpo', 'dp_operator', 'specialist_offshore'),
    ('sdpo', 'dp_operator', 'specialist_offshore'),
    ('dynamic positioning operator', 'dp_operator', 'specialist_offshore'),
    ('senior dynamic positioning operator', 'dp_operator', 'specialist_offshore'),
    ('senior dpo', 'dp_operator', 'specialist_offshore'),
    ('offshore crane operator', 'crane_operator', 'specialist_offshore'),
    ('crane op', 'crane_operator', 'specialist_offshore'),
    ('rov pilot', 'rov_pilot', 'specialist_offshore'),
    ('rov technician', 'rov_pilot', 'specialist_offshore'),
    ('bargemaster', 'barge_master', 'specialist_offshore'),
    ('oim', 'oim', 'specialist_offshore'),
    ('tugmaster', 'tug_master', 'specialist_offshore'),
    ('tug captain', 'tug_master', 'specialist_offshore'),
    ('yacht captain', 'yacht_crew', 'specialist_offshore'),
    ('yacht crew', 'yacht_crew', 'specialist_offshore'),
    ('superyacht crew', 'yacht_crew', 'specialist_offshore'),
    ('inland master', 'inland_master', 'specialist_offshore'),
    ('river master', 'inland_master', 'specialist_offshore'),
    ('inland vessel master', 'inland_master', 'specialist_offshore'),
    ('harbour pilot', 'marine_pilot', 'specialist_offshore'),
    ('sea pilot', 'marine_pilot', 'specialist_offshore'),
    ('pilot', 'marine_pilot', 'specialist_offshore'),
    ('tech superintendent', 'technical_superintendent', 'technical_fleet'),
    ('technical super', 'technical_superintendent', 'technical_fleet'),
    ('superintendent engineer', 'technical_superintendent', 'technical_fleet'),
    ('marine super', 'marine_superintendent', 'technical_fleet'),
    ('offshore marine superintendent', 'marine_superintendent', 'technical_fleet'),
    ('fleet director', 'fleet_manager', 'technical_fleet'),
    ('technical director', 'technical_manager', 'technical_fleet'),
    ('vessel manager', 'technical_manager', 'technical_fleet'),
    ('electrical super', 'electrical_superintendent', 'technical_fleet'),
    ('newbuilding superintendent', 'site_superintendent', 'technical_fleet'),
    ('new building superintendent', 'site_superintendent', 'technical_fleet'),
    ('site superintendent', 'site_superintendent', 'technical_fleet'),
    ('dry dock superintendent', 'site_superintendent', 'technical_fleet'),
    ('qhse manager', 'hseq_manager', 'hseq_vetting'),
    ('hsseq manager', 'hseq_manager', 'hseq_vetting'),
    ('hse manager', 'hseq_manager', 'hseq_vetting'),
    ('hsseq superintendent', 'hseq_manager', 'hseq_vetting'),
    ('offshore hse manager', 'hseq_manager', 'hseq_vetting'),
    ('dpa', 'dpa', 'hseq_vetting'),
    ('cso', 'cso', 'hseq_vetting'),
    ('vetting manager', 'vetting_manager', 'hseq_vetting'),
    ('vetting inspector', 'vetting_manager', 'hseq_vetting'),
    ('vetting superintendent', 'vetting_manager', 'hseq_vetting'),
    ('marine assurance manager', 'vetting_manager', 'hseq_vetting'),
    ('sire inspector', 'sire_inspector', 'hseq_vetting'),
    ('cdi inspector', 'sire_inspector', 'hseq_vetting'),
    ('ocimf inspector', 'sire_inspector', 'hseq_vetting'),
    ('hse officer', 'safety_officer', 'hseq_vetting'),
    ('safety superintendent', 'safety_officer', 'hseq_vetting'),
    ('marine operations manager', 'operations_manager', 'operations_commercial'),
    ('ops manager', 'operations_manager', 'operations_commercial'),
    ('voyage operator', 'ship_operator', 'operations_commercial'),
    ('vessel operator', 'ship_operator', 'operations_commercial'),
    ('cargo operator', 'ship_operator', 'operations_commercial'),
    ('chartering manager', 'chartering_manager', 'operations_commercial'),
    ('shipbroker', 'chartering_manager', 'operations_commercial'),
    ('ship broker', 'chartering_manager', 'operations_commercial'),
    ('charterer', 'chartering_manager', 'operations_commercial'),
    ('chartering broker', 'chartering_manager', 'operations_commercial'),
    ('commercial director', 'commercial_manager', 'operations_commercial'),
    ('post fixture executive', 'post_fixture', 'operations_commercial'),
    ('claims executive', 'post_fixture', 'operations_commercial'),
    ('demurrage analyst', 'post_fixture', 'operations_commercial'),
    ('bunker buyer', 'bunker_trader', 'operations_commercial'),
    ('bunker broker', 'bunker_trader', 'operations_commercial'),
    ('crew manager', 'crewing_manager', 'crewing_manning'),
    ('crew superintendent', 'crewing_manager', 'crewing_manning'),
    ('fleet personnel manager', 'crewing_manager', 'crewing_manning'),
    ('crewing executive', 'crew_coordinator', 'crewing_manning'),
    ('crewing officer', 'crew_coordinator', 'crewing_manning'),
    ('manning agency', 'manning_agent', 'crewing_manning'),
    ('manning officer', 'manning_agent', 'crewing_manning'),
    ('travel coordinator', 'travel_logistics', 'crewing_manning'),
    ('crew travel coordinator', 'travel_logistics', 'crewing_manning'),
    ('port marine superintendent', 'port_captain', 'port_terminal_logistics'),
    ('harbor master', 'harbour_master', 'port_terminal_logistics'),
    ('deputy harbour master', 'harbour_master', 'port_terminal_logistics'),
    ('marine terminal superintendent', 'terminal_manager', 'port_terminal_logistics'),
    ('port operations manager', 'terminal_manager', 'port_terminal_logistics'),
    ('freight forwarding executive', 'freight_forwarder', 'port_terminal_logistics'),
    ('nvocc professional', 'freight_forwarder', 'port_terminal_logistics'),
    ('shipping agent', 'shipping_agent', 'port_terminal_logistics'),
    ('ship agent', 'shipping_agent', 'port_terminal_logistics'),
    ('port agent', 'shipping_agent', 'port_terminal_logistics'),
    ('customs agent', 'shipping_agent', 'port_terminal_logistics'),
    ('customs broker', 'shipping_agent', 'port_terminal_logistics'),
    ('logistics manager', 'logistics_executive', 'port_terminal_logistics'),
    ('logistics coordinator', 'logistics_executive', 'port_terminal_logistics'),
    ('cargo surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('hull surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('condition surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('marine warranty surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('classification surveyor', 'class_surveyor', 'survey_class_legal_insurance'),
    ('flag state surveyor', 'class_surveyor', 'survey_class_legal_insurance'),
    ('maritime consultant', 'marine_consultant', 'survey_class_legal_insurance'),
    ('maritime lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('admiralty lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('shipping lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('p and i executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('p and i claims executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('p and i claims manager', 'pi_insurance', 'survey_class_legal_insurance'),
    ('insurance executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('marine underwriter', 'pi_insurance', 'survey_class_legal_insurance'),
    ('marine insurance broker', 'pi_insurance', 'survey_class_legal_insurance'),
    ('shipyard manager', 'shipyard_project_manager', 'shipyard_engineering'),
    ('yard project manager', 'shipyard_project_manager', 'shipyard_engineering'),
    ('shore marine engineer', 'marine_engineer_shore', 'shipyard_engineering'),
    ('port engineer', 'marine_engineer_shore', 'shipyard_engineering'),
    ('ship repair manager', 'repair_manager', 'shipyard_engineering'),
    ('director', 'director_ceo', 'management'),
    ('ceo', 'director_ceo', 'management'),
    ('managing director', 'director_ceo', 'management'),
    ('md', 'director_ceo', 'management'),
    ('gm', 'general_manager', 'management'),
    ('head of department', 'department_head', 'management'),
    ('hod', 'department_head', 'management'),
    ('talent acquisition manager', 'recruitment_manager', 'recruitment_hr'),
    ('recruiter', 'recruiter', 'recruitment_hr'),
    ('talent acquisition', 'recruiter', 'recruitment_hr'),
    ('maritime recruiter', 'recruiter', 'recruitment_hr'),
    ('crewing recruiter', 'recruiter', 'recruitment_hr'),
    ('human resources manager', 'hr_manager', 'recruitment_hr'),
    ('maritime hr professional', 'hr_executive', 'recruitment_hr'),
    ('hr officer', 'hr_executive', 'recruitment_hr'),
    ('payroll officer', 'payroll_compliance', 'recruitment_hr'),
    ('compliance officer', 'payroll_compliance', 'recruitment_hr'),
    ('principal', 'institute_head', 'training'),
    ('institute head', 'institute_head', 'training'),
    ('senior faculty', 'senior_faculty', 'training'),
    ('lecturer', 'senior_faculty', 'training'),
    ('maritime academy faculty', 'senior_faculty', 'training'),
    ('nautical instructor', 'senior_faculty', 'training'),
    ('engineering instructor', 'senior_faculty', 'training'),
    ('stcw instructor', 'stcw_instructor', 'training'),
    ('maritime trainer', 'stcw_instructor', 'training'),
    ('stcw assessor', 'assessor_examiner', 'training'),
    ('examiner', 'assessor_examiner', 'training'),
    ('assessor', 'assessor_examiner', 'training'),
    ('course creator', 'online_course_creator', 'training'),
    ('coach', 'online_course_creator', 'training'),
    ('soft skills trainer', 'wellbeing_trainer', 'training'),
    ('wellbeing trainer', 'wellbeing_trainer', 'training')
),
role_catalog(role_key, department_key, canonical_key) as (
  values
    ('master', 'deck_officers', 'master'),
    ('chief_officer', 'deck_officers', 'chief_officer'),
    ('second_officer', 'deck_officers', 'second_officer'),
    ('third_officer', 'deck_officers', 'third_officer'),
    ('junior_deck_officer', 'deck_officers', 'junior_deck_officer'),
    ('deck_cadet', 'deck_officers', 'deck_cadet'),
    ('bosun', 'deck_ratings', 'bosun'),
    ('pumpman', 'deck_ratings', 'pumpman'),
    ('able_seaman', 'deck_ratings', 'able_seaman'),
    ('ordinary_seaman', 'deck_ratings', 'ordinary_seaman'),
    ('deck_trainee', 'deck_ratings', 'deck_trainee'),
    ('chief_engineer', 'engine_officers', 'chief_engineer'),
    ('second_engineer', 'engine_officers', 'second_engineer'),
    ('third_engineer', 'engine_officers', 'third_engineer'),
    ('fourth_engineer', 'engine_officers', 'fourth_engineer'),
    ('junior_engineer', 'engine_officers', 'junior_engineer'),
    ('engine_cadet', 'engine_officers', 'engine_cadet'),
    ('eto', 'engine_officers', 'eto'),
    ('electrical_officer', 'engine_officers', 'electrical_officer'),
    ('gas_engineer', 'engine_officers', 'gas_engineer'),
    ('fitter', 'engine_ratings', 'fitter'),
    ('motorman', 'engine_ratings', 'motorman'),
    ('oiler', 'engine_ratings', 'oiler'),
    ('wiper', 'engine_ratings', 'wiper'),
    ('engine_trainee', 'engine_ratings', 'engine_trainee'),
    ('electrician', 'engine_ratings', 'electrician'),
    ('chief_cook', 'catering', 'chief_cook'),
    ('cook', 'catering', 'cook'),
    ('second_cook', 'catering', 'second_cook'),
    ('messman', 'catering', 'messman'),
    ('chief_steward', 'catering', 'chief_steward'),
    ('steward', 'catering', 'steward'),
    ('hotel_purser', 'catering', 'hotel_purser'),
    ('dp_operator', 'specialist_offshore', 'dp_operator'),
    ('crane_operator', 'specialist_offshore', 'crane_operator'),
    ('rov_pilot', 'specialist_offshore', 'rov_pilot'),
    ('barge_master', 'specialist_offshore', 'barge_master'),
    ('oim', 'specialist_offshore', 'oim'),
    ('tug_master', 'specialist_offshore', 'tug_master'),
    ('yacht_crew', 'specialist_offshore', 'yacht_crew'),
    ('inland_master', 'specialist_offshore', 'inland_master'),
    ('marine_pilot', 'specialist_offshore', 'marine_pilot'),
    ('technical_superintendent', 'technical_fleet', 'technical_superintendent'),
    ('marine_superintendent', 'technical_fleet', 'marine_superintendent'),
    ('fleet_manager', 'technical_fleet', 'fleet_manager'),
    ('technical_manager', 'technical_fleet', 'technical_manager'),
    ('electrical_superintendent', 'technical_fleet', 'electrical_superintendent'),
    ('site_superintendent', 'technical_fleet', 'site_superintendent'),
    ('hseq_manager', 'hseq_vetting', 'hseq_manager'),
    ('dpa', 'hseq_vetting', 'dpa'),
    ('cso', 'hseq_vetting', 'cso'),
    ('vetting_manager', 'hseq_vetting', 'vetting_manager'),
    ('sire_inspector', 'hseq_vetting', 'sire_inspector'),
    ('safety_officer', 'hseq_vetting', 'safety_officer'),
    ('operations_manager', 'operations_commercial', 'operations_manager'),
    ('ship_operator', 'operations_commercial', 'ship_operator'),
    ('chartering_manager', 'operations_commercial', 'chartering_manager'),
    ('commercial_manager', 'operations_commercial', 'commercial_manager'),
    ('post_fixture', 'operations_commercial', 'post_fixture'),
    ('bunker_trader', 'operations_commercial', 'bunker_trader'),
    ('crewing_manager', 'crewing_manning', 'crewing_manager'),
    ('crew_coordinator', 'crewing_manning', 'crew_coordinator'),
    ('manning_agent', 'crewing_manning', 'manning_agent'),
    ('travel_logistics', 'crewing_manning', 'travel_logistics'),
    ('port_captain', 'port_terminal_logistics', 'port_captain'),
    ('harbour_master', 'port_terminal_logistics', 'harbour_master'),
    ('terminal_manager', 'port_terminal_logistics', 'terminal_manager'),
    ('port_marine_pilot', 'port_terminal_logistics', 'marine_pilot'),
    ('freight_forwarder', 'port_terminal_logistics', 'freight_forwarder'),
    ('shipping_agent', 'port_terminal_logistics', 'shipping_agent'),
    ('logistics_executive', 'port_terminal_logistics', 'logistics_executive'),
    ('marine_surveyor', 'survey_class_legal_insurance', 'marine_surveyor'),
    ('class_surveyor', 'survey_class_legal_insurance', 'class_surveyor'),
    ('marine_consultant', 'survey_class_legal_insurance', 'marine_consultant'),
    ('marine_lawyer', 'survey_class_legal_insurance', 'marine_lawyer'),
    ('pi_insurance', 'survey_class_legal_insurance', 'pi_insurance'),
    ('average_adjuster', 'survey_class_legal_insurance', 'average_adjuster'),
    ('naval_architect', 'shipyard_engineering', 'naval_architect'),
    ('shipyard_project_manager', 'shipyard_engineering', 'shipyard_project_manager'),
    ('marine_engineer_shore', 'shipyard_engineering', 'marine_engineer_shore'),
    ('repair_manager', 'shipyard_engineering', 'repair_manager'),
    ('director_ceo', 'management', 'director_ceo'),
    ('general_manager', 'management', 'general_manager'),
    ('department_head', 'management', 'department_head'),
    ('hr_crewing_manager', 'recruitment_hr', 'crewing_manager'),
    ('recruitment_manager', 'recruitment_hr', 'recruitment_manager'),
    ('recruiter', 'recruitment_hr', 'recruiter'),
    ('hr_manager', 'recruitment_hr', 'hr_manager'),
    ('hr_executive', 'recruitment_hr', 'hr_executive'),
    ('manning_agency_owner', 'recruitment_hr', 'manning_agent'),
    ('hr_crew_coordinator', 'recruitment_hr', 'crew_coordinator'),
    ('payroll_compliance', 'recruitment_hr', 'payroll_compliance'),
    ('institute_head', 'training', 'institute_head'),
    ('senior_faculty', 'training', 'senior_faculty'),
    ('simulator_instructor', 'training', 'simulator_instructor'),
    ('stcw_instructor', 'training', 'stcw_instructor'),
    ('assessor_examiner', 'training', 'assessor_examiner'),
    ('online_course_creator', 'training', 'online_course_creator'),
    ('mentor', 'training', 'mentor'),
    ('wellbeing_trainer', 'training', 'wellbeing_trainer')
),
persona_departments(persona, department_key) as (
  values
    ('seafarer', 'deck_officers'),
    ('seafarer', 'deck_ratings'),
    ('seafarer', 'engine_officers'),
    ('seafarer', 'engine_ratings'),
    ('seafarer', 'catering'),
    ('seafarer', 'specialist_offshore'),
    ('shore_professional', 'technical_fleet'),
    ('shore_professional', 'hseq_vetting'),
    ('shore_professional', 'operations_commercial'),
    ('shore_professional', 'crewing_manning'),
    ('shore_professional', 'port_terminal_logistics'),
    ('shore_professional', 'survey_class_legal_insurance'),
    ('shore_professional', 'shipyard_engineering'),
    ('shore_professional', 'management'),
    ('recruiter_hr', 'recruitment_hr'),
    ('trainer_instructor', 'training')
),
source as (
  select
    p.id,
    coalesce(
      p.persona,
      case p.profile_type::text
        when 'seafarer' then 'seafarer'
        when 'recruiter' then 'recruiter_hr'
        when 'trainer' then 'trainer_instructor'
        else 'shore_professional'
      end
    ) as persona,
    m.role_key as mapped_key
  from public.profiles p
  join public.maritime_profiles mp on mp.user_id = p.id
  join role_map m on m.rank_text = btrim(regexp_replace(lower(replace(mp.rank, '&', ' and ')), '[^a-z0-9]+', ' ', 'g'))
  where p.role_key is null
    and mp.rank is not null
),
resolved as (
  select distinct on (s.id) s.id, c.role_key, c.department_key
  from source s
  join role_catalog c on c.canonical_key = s.mapped_key
  join persona_departments pd on pd.persona = s.persona and pd.department_key = c.department_key
  order by s.id, (c.role_key = s.mapped_key) desc, c.role_key
)
update public.profiles p
set role_key = r.role_key,
    role_department_key = r.department_key
from resolved r
where p.id = r.id
  and p.role_key is null;
-- statement-breakpoint

with role_map(rank_text, role_key, department_key) as (
  values
    ('master captain', 'master', 'deck_officers'),
    ('chief officer', 'chief_officer', 'deck_officers'),
    ('second officer', 'second_officer', 'deck_officers'),
    ('third officer', 'third_officer', 'deck_officers'),
    ('junior officer fourth officer', 'junior_deck_officer', 'deck_officers'),
    ('deck cadet trainee officer', 'deck_cadet', 'deck_officers'),
    ('bosun', 'bosun', 'deck_ratings'),
    ('pumpman', 'pumpman', 'deck_ratings'),
    ('able seaman ab', 'able_seaman', 'deck_ratings'),
    ('able seaman', 'able_seaman', 'deck_ratings'),
    ('ordinary seaman os', 'ordinary_seaman', 'deck_ratings'),
    ('ordinary seaman', 'ordinary_seaman', 'deck_ratings'),
    ('deck trainee', 'deck_trainee', 'deck_ratings'),
    ('chief engineer', 'chief_engineer', 'engine_officers'),
    ('second engineer 2nd engineer', 'second_engineer', 'engine_officers'),
    ('second engineer', 'second_engineer', 'engine_officers'),
    ('third engineer 3rd engineer', 'third_engineer', 'engine_officers'),
    ('third engineer', 'third_engineer', 'engine_officers'),
    ('fourth engineer 4th engineer', 'fourth_engineer', 'engine_officers'),
    ('fourth engineer', 'fourth_engineer', 'engine_officers'),
    ('junior engineer fifth engineer', 'junior_engineer', 'engine_officers'),
    ('engine cadet trainee engineer', 'engine_cadet', 'engine_officers'),
    ('electro technical officer eto', 'eto', 'engine_officers'),
    ('electro technical officer', 'eto', 'engine_officers'),
    ('electrical officer', 'electrical_officer', 'engine_officers'),
    ('gas engineer lng lpg', 'gas_engineer', 'engine_officers'),
    ('gas engineer', 'gas_engineer', 'engine_officers'),
    ('fitter', 'fitter', 'engine_ratings'),
    ('motorman', 'motorman', 'engine_ratings'),
    ('oiler', 'oiler', 'engine_ratings'),
    ('wiper', 'wiper', 'engine_ratings'),
    ('engine trainee', 'engine_trainee', 'engine_ratings'),
    ('electrician electro technical rating', 'electrician', 'engine_ratings'),
    ('chief cook', 'chief_cook', 'catering'),
    ('cook', 'cook', 'catering'),
    ('second cook', 'second_cook', 'catering'),
    ('messman', 'messman', 'catering'),
    ('chief steward', 'chief_steward', 'catering'),
    ('steward', 'steward', 'catering'),
    ('hotel purser staff', 'hotel_purser', 'catering'),
    ('dp operator dpo sdpo', 'dp_operator', 'specialist_offshore'),
    ('dp operator', 'dp_operator', 'specialist_offshore'),
    ('crane operator', 'crane_operator', 'specialist_offshore'),
    ('rov pilot technician', 'rov_pilot', 'specialist_offshore'),
    ('barge master', 'barge_master', 'specialist_offshore'),
    ('offshore installation manager oim', 'oim', 'specialist_offshore'),
    ('offshore installation manager', 'oim', 'specialist_offshore'),
    ('tug master', 'tug_master', 'specialist_offshore'),
    ('yacht captain crew', 'yacht_crew', 'specialist_offshore'),
    ('inland river master', 'inland_master', 'specialist_offshore'),
    ('marine pilot', 'marine_pilot', 'specialist_offshore'),
    ('technical superintendent', 'technical_superintendent', 'technical_fleet'),
    ('marine superintendent', 'marine_superintendent', 'technical_fleet'),
    ('fleet manager', 'fleet_manager', 'technical_fleet'),
    ('technical manager', 'technical_manager', 'technical_fleet'),
    ('electrical superintendent', 'electrical_superintendent', 'technical_fleet'),
    ('new building site superintendent', 'site_superintendent', 'technical_fleet'),
    ('hseq manager', 'hseq_manager', 'hseq_vetting'),
    ('designated person ashore dpa', 'dpa', 'hseq_vetting'),
    ('designated person ashore', 'dpa', 'hseq_vetting'),
    ('company security officer cso', 'cso', 'hseq_vetting'),
    ('company security officer', 'cso', 'hseq_vetting'),
    ('vetting manager inspector', 'vetting_manager', 'hseq_vetting'),
    ('sire cdi inspector', 'sire_inspector', 'hseq_vetting'),
    ('safety officer', 'safety_officer', 'hseq_vetting'),
    ('operations manager', 'operations_manager', 'operations_commercial'),
    ('ship operator', 'ship_operator', 'operations_commercial'),
    ('chartering manager broker', 'chartering_manager', 'operations_commercial'),
    ('commercial manager', 'commercial_manager', 'operations_commercial'),
    ('post fixture claims executive', 'post_fixture', 'operations_commercial'),
    ('bunker trader', 'bunker_trader', 'operations_commercial'),
    ('crewing manager', 'crewing_manager', 'crewing_manning'),
    ('crew coordinator', 'crew_coordinator', 'crewing_manning'),
    ('manning agent', 'manning_agent', 'crewing_manning'),
    ('travel logistics coordinator', 'travel_logistics', 'crewing_manning'),
    ('port captain', 'port_captain', 'port_terminal_logistics'),
    ('harbour master', 'harbour_master', 'port_terminal_logistics'),
    ('terminal manager', 'terminal_manager', 'port_terminal_logistics'),
    ('freight forwarder', 'freight_forwarder', 'port_terminal_logistics'),
    ('customs shipping agent', 'shipping_agent', 'port_terminal_logistics'),
    ('logistics executive', 'logistics_executive', 'port_terminal_logistics'),
    ('marine surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('class surveyor', 'class_surveyor', 'survey_class_legal_insurance'),
    ('marine consultant', 'marine_consultant', 'survey_class_legal_insurance'),
    ('marine lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('p and i insurance executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('average adjuster', 'average_adjuster', 'survey_class_legal_insurance'),
    ('naval architect', 'naval_architect', 'shipyard_engineering'),
    ('shipyard project manager', 'shipyard_project_manager', 'shipyard_engineering'),
    ('marine engineer shore', 'marine_engineer_shore', 'shipyard_engineering'),
    ('marine engineer', 'marine_engineer_shore', 'shipyard_engineering'),
    ('repair manager', 'repair_manager', 'shipyard_engineering'),
    ('director ceo', 'director_ceo', 'management'),
    ('general manager', 'general_manager', 'management'),
    ('department head', 'department_head', 'management'),
    ('recruitment manager', 'recruitment_manager', 'recruitment_hr'),
    ('recruiter talent acquisition', 'recruiter', 'recruitment_hr'),
    ('hr manager', 'hr_manager', 'recruitment_hr'),
    ('hr executive', 'hr_executive', 'recruitment_hr'),
    ('payroll compliance officer', 'payroll_compliance', 'recruitment_hr'),
    ('maritime training institute head principal', 'institute_head', 'training'),
    ('senior faculty lecturer', 'senior_faculty', 'training'),
    ('simulator instructor bridge engine dp', 'simulator_instructor', 'training'),
    ('simulator instructor', 'simulator_instructor', 'training'),
    ('stcw course instructor bst aff medical', 'stcw_instructor', 'training'),
    ('stcw course instructor', 'stcw_instructor', 'training'),
    ('assessor examiner', 'assessor_examiner', 'training'),
    ('online course creator coach', 'online_course_creator', 'training'),
    ('mentor ex seafarer', 'mentor', 'training'),
    ('mentor', 'mentor', 'training'),
    ('soft skills wellbeing trainer', 'wellbeing_trainer', 'training'),
    ('captain', 'master', 'deck_officers'),
    ('master mariner', 'master', 'deck_officers'),
    ('master', 'master', 'deck_officers'),
    ('capt', 'master', 'deck_officers'),
    ('ship master', 'master', 'deck_officers'),
    ('shipmaster', 'master', 'deck_officers'),
    ('chief mate', 'chief_officer', 'deck_officers'),
    ('c o', 'chief_officer', 'deck_officers'),
    ('co', 'chief_officer', 'deck_officers'),
    ('first officer', 'chief_officer', 'deck_officers'),
    ('first mate', 'chief_officer', 'deck_officers'),
    ('chief off', 'chief_officer', 'deck_officers'),
    ('2nd officer', 'second_officer', 'deck_officers'),
    ('2 o', 'second_officer', 'deck_officers'),
    ('2nd mate', 'second_officer', 'deck_officers'),
    ('second mate', 'second_officer', 'deck_officers'),
    ('2nd off', 'second_officer', 'deck_officers'),
    ('3rd officer', 'third_officer', 'deck_officers'),
    ('3 o', 'third_officer', 'deck_officers'),
    ('3rd mate', 'third_officer', 'deck_officers'),
    ('third mate', 'third_officer', 'deck_officers'),
    ('3rd off', 'third_officer', 'deck_officers'),
    ('junior officer', 'junior_deck_officer', 'deck_officers'),
    ('fourth officer', 'junior_deck_officer', 'deck_officers'),
    ('4th officer', 'junior_deck_officer', 'deck_officers'),
    ('4 o', 'junior_deck_officer', 'deck_officers'),
    ('junior deck officer', 'junior_deck_officer', 'deck_officers'),
    ('4th mate', 'junior_deck_officer', 'deck_officers'),
    ('deck cadet', 'deck_cadet', 'deck_officers'),
    ('trainee officer', 'deck_cadet', 'deck_officers'),
    ('trainee navigating officer', 'deck_cadet', 'deck_officers'),
    ('tno', 'deck_cadet', 'deck_officers'),
    ('nautical cadet', 'deck_cadet', 'deck_officers'),
    ('boatswain', 'bosun', 'deck_ratings'),
    ('bos n', 'bosun', 'deck_ratings'),
    ('pump man', 'pumpman', 'deck_ratings'),
    ('ab', 'able_seaman', 'deck_ratings'),
    ('a b', 'able_seaman', 'deck_ratings'),
    ('able seafarer deck', 'able_seaman', 'deck_ratings'),
    ('able bodied seaman', 'able_seaman', 'deck_ratings'),
    ('os', 'ordinary_seaman', 'deck_ratings'),
    ('o s', 'ordinary_seaman', 'deck_ratings'),
    ('trainee seaman', 'deck_trainee', 'deck_ratings'),
    ('deck boy', 'deck_trainee', 'deck_ratings'),
    ('tos', 'deck_trainee', 'deck_ratings'),
    ('trainee os', 'deck_trainee', 'deck_ratings'),
    ('c e', 'chief_engineer', 'engine_officers'),
    ('ce', 'chief_engineer', 'engine_officers'),
    ('chief engg', 'chief_engineer', 'engine_officers'),
    ('chief eng', 'chief_engineer', 'engine_officers'),
    ('chief engineer officer', 'chief_engineer', 'engine_officers'),
    ('2nd engineer', 'second_engineer', 'engine_officers'),
    ('2 e', 'second_engineer', 'engine_officers'),
    ('2nd engg', 'second_engineer', 'engine_officers'),
    ('2nd eng', 'second_engineer', 'engine_officers'),
    ('first engineer', 'second_engineer', 'engine_officers'),
    ('1st engineer', 'second_engineer', 'engine_officers'),
    ('3rd engineer', 'third_engineer', 'engine_officers'),
    ('3 e', 'third_engineer', 'engine_officers'),
    ('3rd engg', 'third_engineer', 'engine_officers'),
    ('3rd eng', 'third_engineer', 'engine_officers'),
    ('4th engineer', 'fourth_engineer', 'engine_officers'),
    ('4 e', 'fourth_engineer', 'engine_officers'),
    ('4th engg', 'fourth_engineer', 'engine_officers'),
    ('4th eng', 'fourth_engineer', 'engine_officers'),
    ('junior engineer', 'junior_engineer', 'engine_officers'),
    ('fifth engineer', 'junior_engineer', 'engine_officers'),
    ('5th engineer', 'junior_engineer', 'engine_officers'),
    ('5 e', 'junior_engineer', 'engine_officers'),
    ('je', 'junior_engineer', 'engine_officers'),
    ('engine cadet', 'engine_cadet', 'engine_officers'),
    ('trainee engineer', 'engine_cadet', 'engine_officers'),
    ('trainee marine engineer', 'engine_cadet', 'engine_officers'),
    ('tme', 'engine_cadet', 'engine_officers'),
    ('eto', 'eto', 'engine_officers'),
    ('electrical engineer', 'eto', 'engine_officers'),
    ('electro officer', 'electrical_officer', 'engine_officers'),
    ('elec officer', 'electrical_officer', 'engine_officers'),
    ('lng engineer', 'gas_engineer', 'engine_officers'),
    ('lpg engineer', 'gas_engineer', 'engine_officers'),
    ('cargo engineer', 'gas_engineer', 'engine_officers'),
    ('engine fitter', 'fitter', 'engine_ratings'),
    ('motor man', 'motorman', 'engine_ratings'),
    ('greaser', 'oiler', 'engine_ratings'),
    ('trainee wiper', 'engine_trainee', 'engine_ratings'),
    ('engine boy', 'engine_trainee', 'engine_ratings'),
    ('electrician', 'electrician', 'engine_ratings'),
    ('electro technical rating', 'electrician', 'engine_ratings'),
    ('etr', 'electrician', 'engine_ratings'),
    ('ch cook', 'chief_cook', 'catering'),
    ('head cook', 'chief_cook', 'catering'),
    ('ship cook', 'cook', 'catering'),
    ('2nd cook', 'second_cook', 'catering'),
    ('assistant cook', 'second_cook', 'catering'),
    ('mess man', 'messman', 'catering'),
    ('mess boy', 'messman', 'catering'),
    ('general steward', 'messman', 'catering'),
    ('gs', 'messman', 'catering'),
    ('ch steward', 'chief_steward', 'catering'),
    ('head steward', 'chief_steward', 'catering'),
    ('stewardess', 'steward', 'catering'),
    ('purser', 'hotel_purser', 'catering'),
    ('hotel manager', 'hotel_purser', 'catering'),
    ('hotel staff', 'hotel_purser', 'catering'),
    ('purser staff', 'hotel_purser', 'catering'),
    ('dpo', 'dp_operator', 'specialist_offshore'),
    ('sdpo', 'dp_operator', 'specialist_offshore'),
    ('dynamic positioning operator', 'dp_operator', 'specialist_offshore'),
    ('senior dynamic positioning operator', 'dp_operator', 'specialist_offshore'),
    ('senior dpo', 'dp_operator', 'specialist_offshore'),
    ('offshore crane operator', 'crane_operator', 'specialist_offshore'),
    ('crane op', 'crane_operator', 'specialist_offshore'),
    ('rov pilot', 'rov_pilot', 'specialist_offshore'),
    ('rov technician', 'rov_pilot', 'specialist_offshore'),
    ('bargemaster', 'barge_master', 'specialist_offshore'),
    ('oim', 'oim', 'specialist_offshore'),
    ('tugmaster', 'tug_master', 'specialist_offshore'),
    ('tug captain', 'tug_master', 'specialist_offshore'),
    ('yacht captain', 'yacht_crew', 'specialist_offshore'),
    ('yacht crew', 'yacht_crew', 'specialist_offshore'),
    ('superyacht crew', 'yacht_crew', 'specialist_offshore'),
    ('inland master', 'inland_master', 'specialist_offshore'),
    ('river master', 'inland_master', 'specialist_offshore'),
    ('inland vessel master', 'inland_master', 'specialist_offshore'),
    ('harbour pilot', 'marine_pilot', 'specialist_offshore'),
    ('sea pilot', 'marine_pilot', 'specialist_offshore'),
    ('pilot', 'marine_pilot', 'specialist_offshore'),
    ('tech superintendent', 'technical_superintendent', 'technical_fleet'),
    ('technical super', 'technical_superintendent', 'technical_fleet'),
    ('superintendent engineer', 'technical_superintendent', 'technical_fleet'),
    ('marine super', 'marine_superintendent', 'technical_fleet'),
    ('offshore marine superintendent', 'marine_superintendent', 'technical_fleet'),
    ('fleet director', 'fleet_manager', 'technical_fleet'),
    ('technical director', 'technical_manager', 'technical_fleet'),
    ('vessel manager', 'technical_manager', 'technical_fleet'),
    ('electrical super', 'electrical_superintendent', 'technical_fleet'),
    ('newbuilding superintendent', 'site_superintendent', 'technical_fleet'),
    ('new building superintendent', 'site_superintendent', 'technical_fleet'),
    ('site superintendent', 'site_superintendent', 'technical_fleet'),
    ('dry dock superintendent', 'site_superintendent', 'technical_fleet'),
    ('qhse manager', 'hseq_manager', 'hseq_vetting'),
    ('hsseq manager', 'hseq_manager', 'hseq_vetting'),
    ('hse manager', 'hseq_manager', 'hseq_vetting'),
    ('hsseq superintendent', 'hseq_manager', 'hseq_vetting'),
    ('offshore hse manager', 'hseq_manager', 'hseq_vetting'),
    ('dpa', 'dpa', 'hseq_vetting'),
    ('cso', 'cso', 'hseq_vetting'),
    ('vetting manager', 'vetting_manager', 'hseq_vetting'),
    ('vetting inspector', 'vetting_manager', 'hseq_vetting'),
    ('vetting superintendent', 'vetting_manager', 'hseq_vetting'),
    ('marine assurance manager', 'vetting_manager', 'hseq_vetting'),
    ('sire inspector', 'sire_inspector', 'hseq_vetting'),
    ('cdi inspector', 'sire_inspector', 'hseq_vetting'),
    ('ocimf inspector', 'sire_inspector', 'hseq_vetting'),
    ('hse officer', 'safety_officer', 'hseq_vetting'),
    ('safety superintendent', 'safety_officer', 'hseq_vetting'),
    ('marine operations manager', 'operations_manager', 'operations_commercial'),
    ('ops manager', 'operations_manager', 'operations_commercial'),
    ('voyage operator', 'ship_operator', 'operations_commercial'),
    ('vessel operator', 'ship_operator', 'operations_commercial'),
    ('cargo operator', 'ship_operator', 'operations_commercial'),
    ('chartering manager', 'chartering_manager', 'operations_commercial'),
    ('shipbroker', 'chartering_manager', 'operations_commercial'),
    ('ship broker', 'chartering_manager', 'operations_commercial'),
    ('charterer', 'chartering_manager', 'operations_commercial'),
    ('chartering broker', 'chartering_manager', 'operations_commercial'),
    ('commercial director', 'commercial_manager', 'operations_commercial'),
    ('post fixture executive', 'post_fixture', 'operations_commercial'),
    ('claims executive', 'post_fixture', 'operations_commercial'),
    ('demurrage analyst', 'post_fixture', 'operations_commercial'),
    ('bunker buyer', 'bunker_trader', 'operations_commercial'),
    ('bunker broker', 'bunker_trader', 'operations_commercial'),
    ('crew manager', 'crewing_manager', 'crewing_manning'),
    ('crew superintendent', 'crewing_manager', 'crewing_manning'),
    ('fleet personnel manager', 'crewing_manager', 'crewing_manning'),
    ('crewing executive', 'crew_coordinator', 'crewing_manning'),
    ('crewing officer', 'crew_coordinator', 'crewing_manning'),
    ('manning agency', 'manning_agent', 'crewing_manning'),
    ('manning officer', 'manning_agent', 'crewing_manning'),
    ('travel coordinator', 'travel_logistics', 'crewing_manning'),
    ('crew travel coordinator', 'travel_logistics', 'crewing_manning'),
    ('port marine superintendent', 'port_captain', 'port_terminal_logistics'),
    ('harbor master', 'harbour_master', 'port_terminal_logistics'),
    ('deputy harbour master', 'harbour_master', 'port_terminal_logistics'),
    ('marine terminal superintendent', 'terminal_manager', 'port_terminal_logistics'),
    ('port operations manager', 'terminal_manager', 'port_terminal_logistics'),
    ('freight forwarding executive', 'freight_forwarder', 'port_terminal_logistics'),
    ('nvocc professional', 'freight_forwarder', 'port_terminal_logistics'),
    ('shipping agent', 'shipping_agent', 'port_terminal_logistics'),
    ('ship agent', 'shipping_agent', 'port_terminal_logistics'),
    ('port agent', 'shipping_agent', 'port_terminal_logistics'),
    ('customs agent', 'shipping_agent', 'port_terminal_logistics'),
    ('customs broker', 'shipping_agent', 'port_terminal_logistics'),
    ('logistics manager', 'logistics_executive', 'port_terminal_logistics'),
    ('logistics coordinator', 'logistics_executive', 'port_terminal_logistics'),
    ('cargo surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('hull surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('condition surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('marine warranty surveyor', 'marine_surveyor', 'survey_class_legal_insurance'),
    ('classification surveyor', 'class_surveyor', 'survey_class_legal_insurance'),
    ('flag state surveyor', 'class_surveyor', 'survey_class_legal_insurance'),
    ('maritime consultant', 'marine_consultant', 'survey_class_legal_insurance'),
    ('maritime lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('admiralty lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('shipping lawyer', 'marine_lawyer', 'survey_class_legal_insurance'),
    ('p and i executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('p and i claims executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('p and i claims manager', 'pi_insurance', 'survey_class_legal_insurance'),
    ('insurance executive', 'pi_insurance', 'survey_class_legal_insurance'),
    ('marine underwriter', 'pi_insurance', 'survey_class_legal_insurance'),
    ('marine insurance broker', 'pi_insurance', 'survey_class_legal_insurance'),
    ('shipyard manager', 'shipyard_project_manager', 'shipyard_engineering'),
    ('yard project manager', 'shipyard_project_manager', 'shipyard_engineering'),
    ('shore marine engineer', 'marine_engineer_shore', 'shipyard_engineering'),
    ('port engineer', 'marine_engineer_shore', 'shipyard_engineering'),
    ('ship repair manager', 'repair_manager', 'shipyard_engineering'),
    ('director', 'director_ceo', 'management'),
    ('ceo', 'director_ceo', 'management'),
    ('managing director', 'director_ceo', 'management'),
    ('md', 'director_ceo', 'management'),
    ('gm', 'general_manager', 'management'),
    ('head of department', 'department_head', 'management'),
    ('hod', 'department_head', 'management'),
    ('talent acquisition manager', 'recruitment_manager', 'recruitment_hr'),
    ('recruiter', 'recruiter', 'recruitment_hr'),
    ('talent acquisition', 'recruiter', 'recruitment_hr'),
    ('maritime recruiter', 'recruiter', 'recruitment_hr'),
    ('crewing recruiter', 'recruiter', 'recruitment_hr'),
    ('human resources manager', 'hr_manager', 'recruitment_hr'),
    ('maritime hr professional', 'hr_executive', 'recruitment_hr'),
    ('hr officer', 'hr_executive', 'recruitment_hr'),
    ('payroll officer', 'payroll_compliance', 'recruitment_hr'),
    ('compliance officer', 'payroll_compliance', 'recruitment_hr'),
    ('principal', 'institute_head', 'training'),
    ('institute head', 'institute_head', 'training'),
    ('senior faculty', 'senior_faculty', 'training'),
    ('lecturer', 'senior_faculty', 'training'),
    ('maritime academy faculty', 'senior_faculty', 'training'),
    ('nautical instructor', 'senior_faculty', 'training'),
    ('engineering instructor', 'senior_faculty', 'training'),
    ('stcw instructor', 'stcw_instructor', 'training'),
    ('maritime trainer', 'stcw_instructor', 'training'),
    ('stcw assessor', 'assessor_examiner', 'training'),
    ('examiner', 'assessor_examiner', 'training'),
    ('assessor', 'assessor_examiner', 'training'),
    ('course creator', 'online_course_creator', 'training'),
    ('coach', 'online_course_creator', 'training'),
    ('soft skills trainer', 'wellbeing_trainer', 'training'),
    ('wellbeing trainer', 'wellbeing_trainer', 'training')
),
department_domains(department_key, domain) as (
  values
    ('deck_officers', 'sea'),
    ('deck_ratings', 'sea'),
    ('engine_officers', 'sea'),
    ('engine_ratings', 'sea'),
    ('catering', 'sea'),
    ('specialist_offshore', 'sea'),
    ('technical_fleet', 'shore'),
    ('hseq_vetting', 'shore'),
    ('operations_commercial', 'shore'),
    ('crewing_manning', 'shore'),
    ('port_terminal_logistics', 'shore'),
    ('survey_class_legal_insurance', 'shore'),
    ('shipyard_engineering', 'shore'),
    ('management', 'shore'),
    ('recruitment_hr', 'shore'),
    ('training', 'shore')
)
update public.jobs j
set department_key = m.department_key,
    accepted_role_keys = array[m.role_key]::text[]
from role_map m
join department_domains dd on dd.department_key = m.department_key
where j.department_key is null
  and cardinality(j.accepted_role_keys) = 0
  and j.rank is not null
  and m.rank_text = btrim(regexp_replace(lower(replace(j.rank, '&', ' and ')), '[^a-z0-9]+', ' ', 'g'))
  and dd.domain = coalesce(j.job_domain, 'sea');
-- statement-breakpoint

update public.jobs j
set min_match_to_apply = 0
where j.department_key is null
  and coalesce(j.job_domain, 'sea') = 'shore'
  and j.min_match_to_apply = 70
  and j.created_at < now();
-- statement-breakpoint
