'use client'

import { MediaImage } from '@/components/ui/media-image'
import Link from 'next/link'
import { useRouter } from 'next/navigation'
import type { ReactNode } from 'react'
import { createContext, createElement, useActionState, useEffect, useState } from 'react'
import { Building2, MapPin, Pencil, type LucideProps } from 'lucide-react'
import { organizationPageHref } from '../organization-link'
import { updateProfileIdentitySection, type ProfileInlineActionState } from '../profile-inline-actions'
import { PERSONA_LABELS, type Persona } from '../persona'
import { profileIdentityIcon } from '../persona-icons'
import { personaForProfile } from '../profile-persona-rules'
import type { ContactVisibility, OwnProfile, PublicProfile } from '../types'
import { OrganizationLogo } from './organization-logo'
import type { PickerOrganization } from './organization-picker'
import { OrganizationStatusBadge } from './organization-status-badge'
import { ProfileCardFieldError, ProfileCardForm, profileCardInputClass, profileCardLabelClass, useProfileCardEditor } from './profile-card-editing'
import { PersonaDetailFields, PersonaSelect } from './profile-persona-fields'
import { UsernameField } from './username-field'

const profileTypeLabels: Record<PublicProfile['profileType'], string> = {
  seafarer: 'Seafarer',
  maritime_professional: 'Maritime Professional',
  company: 'Company',
  trainer: 'Trainer',
  mentor: 'Mentor',
  recruiter: 'Recruiter',
  service_provider: 'Maritime Service Provider',
}

const initialState: ProfileInlineActionState = {}

/**
 * Opens the owner's inline header editor (profile type, name, username, headline, location,
 * organization, rank, contact visibility). Provided by ProfileHeader so its `actions` (the phone
 * "…" sheet's "Edit profile") can open it.
 */
export const ProfileIdentityEditorContext = createContext<(() => void) | null>(null)

function initials(name: string) {
  return name
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase())
    .join('')
}

type HeaderProfile = PublicProfile & Partial<Pick<OwnProfile, 'usernameChangeCount' | 'usernameAutoGenerated'>>

/** The header card's edit form: everything the header shows except the photos and network counts. */
function ProfileIdentityEditor({
  profile,
  contactVisibility,
  registeredOrganization,
  onClose,
  onSaved,
  onDirty,
}: {
  profile: HeaderProfile
  contactVisibility: ContactVisibility
  registeredOrganization: PickerOrganization | null
  onClose: () => void
  onSaved: () => void
  onDirty: () => void
}) {
  const organisationAccount = profile.identityRoot === 'organisation'
  const [persona, setPersona] = useState<Persona>(() => personaForProfile(profile))
  const [usernameReady, setUsernameReady] = useState(true)

  async function submitIdentity(previousState: ProfileInlineActionState, formData: FormData) {
    const nextState = await updateProfileIdentitySection(previousState, formData)
    if (nextState.success) onSaved()
    return nextState
  }

  const [state, formAction, pending] = useActionState(submitIdentity, initialState)
  const usernameChangesRemaining = Math.max(0, 2 - (profile.usernameChangeCount ?? 0))
  const usernameAutoGenerated = profile.usernameAutoGenerated === true
  const usernameLocked = usernameChangesRemaining === 0 && !usernameAutoGenerated

  return (
    <ProfileCardForm
      cardId="profile-header"
      label="Edit basic information"
      action={formAction}
      pending={pending}
      onCancel={onClose}
      onDirty={onDirty}
      error={state.error}
      saveDisabled={!usernameReady}
      className="mt-5 rounded-2xl border border-ocean-100 bg-ocean-50/40 p-4 sm:p-5"
    >
      <div className="grid gap-4 sm:grid-cols-2">
        {organisationAccount ? null : (
          <div className="sm:col-span-2">
            <PersonaSelect persona={persona} onChange={setPersona} fieldErrors={state.fieldErrors} />
          </div>
        )}
        <label className={profileCardLabelClass}>
          Full name
          <input name="fullName" required maxLength={120} defaultValue={profile.fullName} className={profileCardInputClass} />
          <ProfileCardFieldError fieldErrors={state.fieldErrors} name="fullName" />
        </label>
        <UsernameField
          initialValue={profile.slug}
          currentUsername={profile.slug}
          serverError={state.fieldErrors?.slug?.[0]}
          changesRemaining={usernameChangesRemaining}
          locked={usernameLocked}
          onReadyChange={setUsernameReady}
          helpText={usernameAutoGenerated
            ? 'We created this username for you when you joined. Changing it once does not count toward your 2 changes.'
            : undefined}
        />
        <label className={profileCardLabelClass}>
          Headline
          <input name="headline" required maxLength={160} defaultValue={profile.headline ?? ''} className={profileCardInputClass} />
          <ProfileCardFieldError fieldErrors={state.fieldErrors} name="headline" />
        </label>
        <label className={profileCardLabelClass}>
          Location
          <input name="location" maxLength={120} defaultValue={profile.location ?? ''} className={profileCardInputClass} />
          <ProfileCardFieldError fieldErrors={state.fieldErrors} name="location" />
        </label>
        <PersonaDetailFields
          persona={persona}
          profile={profile}
          fieldErrors={state.fieldErrors}
          registeredOrganization={registeredOrganization}
        />
        <label className={profileCardLabelClass}>
          Contact visibility
          <select name="contactVisibility" defaultValue={contactVisibility} className={profileCardInputClass}>
            <option value="private">Private</option>
            <option value="members">Members only</option>
            <option value="public">Public</option>
          </select>
          <ProfileCardFieldError fieldErrors={state.fieldErrors} name="contactVisibility" />
        </label>
      </div>
    </ProfileCardForm>
  )
}

export function ProfileHeader({
  profile,
  actions,
  editHref,
  mediaControls,
  avatarControls,
  stats,
  badges,
  contactVisibility = 'members',
  registeredOrganization = null,
}: {
  profile: HeaderProfile
  actions?: ReactNode
  /** Network counts (connections, followers, following), rendered by the page. */
  stats?: ReactNode
  /** Small owner-only status badges, such as "DG profile on file". */
  badges?: ReactNode
  /** Set on the owner's own profile: the header then edits in place. */
  editHref?: string
  mediaControls?: ReactNode
  avatarControls?: ReactNode
  contactVisibility?: ContactVisibility
  /** Back from registering an organization from the picker: open the editor with it linked. */
  registeredOrganization?: PickerOrganization | null
}) {
  const router = useRouter()
  const editor = useProfileCardEditor('profile-header', 'Basic information')
  const editable = Boolean(editHref)
  const editing = editable && editor.editing
  const { open: openEditor } = editor

  useEffect(() => {
    if (editable && registeredOrganization) openEditor()
  }, [editable, registeredOrganization, openEditor])

  function saved() {
    editor.close()
    // Drop ?registered= once the organization is saved, so it is not offered again.
    if (registeredOrganization) router.replace('/profile', { scroll: false })
    else router.refresh()
  }

  const identityLabel = profile.persona ? PERSONA_LABELS[profile.persona] : profile.primaryIdentity ?? profileTypeLabels[profile.profileType]
  const identityIcon = createElement(profileIdentityIcon(profile), {
    'aria-hidden': true,
    'data-testid': 'profile-identity-icon',
    className: 'size-3.5',
  } as LucideProps)
  const secondaryIdentities = profile.secondaryIdentities ?? []

  return (
    <ProfileIdentityEditorContext.Provider value={editable ? openEditor : null}>
    <section data-testid="profile-header-shell" className="overflow-visible rounded-[1.75rem] border border-mist-100 bg-white shadow-[var(--shadow-card)] max-md:-mx-4 max-md:rounded-none max-md:border-x-0 max-md:border-t-0 max-md:shadow-none">
      <div data-testid="profile-header-cover" className="relative h-36 overflow-hidden rounded-t-[1.75rem] bg-[linear-gradient(115deg,var(--navy-950),var(--ocean-700)_58%,var(--teal-500))] max-md:h-28 max-md:rounded-none sm:h-48">
        {profile.coverUrl ? (
          <MediaImage
            src={profile.coverUrl}
            alt={`${profile.fullName} cover photo`}
            fill
            sizes="(max-width: 768px) 100vw, 960px"
            quality={90}
            loading="eager"
            className="object-cover"
          />
        ) : null}
        {mediaControls ? <div className="absolute right-4 top-4 z-10">{mediaControls}</div> : null}
      </div>

      <div className="px-5 pb-6 max-md:px-4 max-md:pb-5 sm:px-8 sm:pb-8">
        <div className="-mt-12 flex items-end justify-between gap-4 sm:-mt-16">
          <div className="relative shrink-0">
            <div
              data-testid="profile-header-avatar"
              className="relative grid size-24 place-items-center overflow-hidden rounded-full border-4 border-white bg-mist-100 text-xl font-semibold text-navy-950 shadow-sm sm:size-32 sm:text-2xl"
            >
              {profile.avatarUrl ? (
                <MediaImage
                  avatar
                  src={profile.avatarUrl}
                  alt={`${profile.fullName} profile photo`}
                  fill
                  sizes="(min-width: 640px) 128px, 96px"
                  loading="eager"
                  fetchPriority="high"
                  className="object-cover"
                  fallback={initials(profile.fullName)}
                />
              ) : (
                initials(profile.fullName)
              )}
            </div>
            {avatarControls ? <div className="absolute -bottom-1 -right-1 z-10">{avatarControls}</div> : null}
          </div>
        </div>

        <div data-testid="profile-header-identity" className="mt-4 max-w-4xl">
          {!editing ? (
            <span className="inline-flex items-center gap-1.5 rounded-full bg-mist-50 px-2.5 py-1 text-xs font-semibold text-ocean-700">
              {identityIcon}
              {identityLabel}
            </span>
          ) : null}

          <div className="mt-2 flex min-w-0 items-center gap-2">
            <h1 className="min-w-0 text-[1.75rem] font-semibold leading-[1.15] tracking-[-.025em] text-navy-950 max-md:text-2xl max-md:font-bold sm:text-[2rem]">
              {profile.fullName}
            </h1>
            {editable && !editing ? (
              <button
                ref={editor.triggerRef}
                type="button"
                onClick={openEditor}
                aria-label="Edit basic information"
                className="inline-flex size-9 shrink-0 items-center justify-center rounded-full border border-mist-200 text-navy-950 hover:border-ocean-500 hover:text-ocean-700 max-md:ml-auto max-md:size-11 max-md:border-transparent focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ocean-600"
              >
                <Pencil aria-hidden="true" className="size-4" />
              </button>
            ) : null}
          </div>
          {!editing ? <p className="mt-1 text-sm font-medium text-muted">@{profile.slug}</p> : null}

          {!editing && secondaryIdentities.length ? (
            <div className="mt-2 flex flex-wrap gap-1.5">
              {secondaryIdentities.map((identity) => (
                <span key={identity} className="rounded-full bg-ocean-50 px-2.5 py-1 text-xs font-medium text-ocean-800">
                  {identity}
                </span>
              ))}
            </div>
          ) : null}

          {!editing && profile.headline ? (
            <p className="mt-3 max-w-3xl text-base font-medium leading-6 text-ink sm:text-[1.05rem]">{profile.headline}</p>
          ) : null}

          {!editing ? (
            <div className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted">
              {profile.location ? (
                <span className="inline-flex items-center gap-1.5">
                  <MapPin aria-hidden="true" className="size-4" />
                  {profile.location}
                </span>
              ) : null}
              {profile.currentOrganization ? (
                <Link
                  href={organizationPageHref(profile.currentOrganization.slug)}
                  data-testid="profile-header-organization"
                  className="inline-flex min-w-0 items-center gap-2 font-semibold text-ocean-700 hover:underline"
                >
                  <OrganizationLogo logoUrl={profile.currentOrganization.logoUrl} size="xs" />
                  <span className="min-w-0 truncate">{profile.currentOrganization.name}</span>
                  <OrganizationStatusBadge organization={profile.currentOrganization} size="sm" />
                </Link>
              ) : profile.currentCompany ? (
                <span className="inline-flex items-center gap-1.5">
                  <Building2 aria-hidden="true" className="size-4" />
                  {profile.currentCompany}
                </span>
              ) : null}
            </div>
          ) : null}

          {!editing && badges ? <div className="mt-3 flex flex-wrap gap-2">{badges}</div> : null}
          {!editing && stats ? stats : null}
        </div>

        {editing ? (
          <ProfileIdentityEditor
            profile={profile}
            contactVisibility={contactVisibility}
            registeredOrganization={registeredOrganization}
            onClose={editor.close}
            onSaved={saved}
            onDirty={editor.markDirty}
          />
        ) : actions ? (
          <div data-testid="profile-header-actions" className="mt-5 w-full max-md:mt-4">
            {actions}
          </div>
        ) : null}
      </div>
    </section>
    </ProfileIdentityEditorContext.Provider>
  )
}
