import assert from 'node:assert/strict'
import fs from 'node:fs'

const sql = fs.readFileSync('infra/aws/database/migrations/0028_deleted_post_recovery.sql', 'utf8')
const script = fs.readFileSync('scripts/aws/deleted-post-recovery-migration.sh', 'utf8')
const guard = fs.readFileSync('scripts/aws/deleted-post-recovery-migration-action.txt', 'utf8').trim()
const workflow = fs.readFileSync('.github/workflows/aws-deleted-post-recovery-migration.yml', 'utf8')

assert.ok(['plan', 'migrate-once'].includes(guard))
assert.match(sql, /add column deleted_by uuid references public\.profiles\(id\) on delete set null/i)
assert.match(sql, /add column deletion_reason text/i)
assert.match(sql, /add column purge_after timestamptz/i)
assert.match(sql, /interval '30 days'/i)
assert.match(sql, /from public\.moderation_actions/i)
assert.match(sql, /action = 'remove'/i)
assert.match(sql, /posts_deletion_reason_check/i)
assert.match(sql, /posts_deletion_metadata_check/i)
assert.match(sql, /posts_deleted_purge_idx/i)
assert.doesNotMatch(sql, /drop table/i)
assert.doesNotMatch(sql, /drop column/i)
assert.doesNotMatch(sql, /truncate/i)
assert.doesNotMatch(sql, /delete from/i)

assert.match(script, /310356785722/)
assert.match(script, /DELETED_POST_RECOVERY_MIGRATION_EXPECTED_SHA/)
assert.match(script, /plan\|migrate-once/)
assert.match(script, /0028_deleted_post_recovery\.sql/)
assert.match(script, /expected exactly five deleted post recovery statements/i)
assert.match(script, /sea-n-shore-deleted-post-recovery-0028/)
assert.match(script, /begin-transaction/)
assert.match(script, /commit-transaction/)
assert.match(script, /rollback-transaction/)
assert.match(script, /DELETED_POST_RECOVERY_MIGRATION_PLAN_ONLY_NO_APPLY/)
assert.match(script, /DELETED_POST_RECOVERY_MIGRATION_APPLY_VERIFIED=true/)
assert.match(script, /DELETED_POST_RECOVERY_MIGRATION_ALREADY_APPLIED=true/)
assert.match(script, /git ls-remote origin refs\/heads\/feat\/aws-native-phase-0-1/)
assert.doesNotMatch(script, /992382634586/)

assert.match(workflow, /Wait for exact-head AWS Infrastructure CI/)
assert.match(workflow, /Guard migration against a moved branch/)
assert.match(workflow, /environment:\s*staging/)
assert.match(workflow, /DELETED_POST_RECOVERY_MIGRATION_EXPECTED_SHA/)
assert.match(workflow, /bash scripts\/aws\/deleted-post-recovery-migration\.sh/)

console.log('DELETED_POST_RECOVERY_MIGRATION_CONTRACT_VERIFIED=true')
