import assert from 'node:assert/strict'
import fs from 'node:fs'

const sql = fs.readFileSync('infra/aws/database/migrations/0025_job_application_cv.sql', 'utf8')
const script = fs.readFileSync('scripts/aws/job-application-cv-migration.sh', 'utf8')
const guard = fs.readFileSync('scripts/aws/job-application-cv-migration-action.txt', 'utf8').trim()
const workflow = fs.readFileSync('.github/workflows/aws-job-application-cv-migration.yml', 'utf8')

assert.ok(['plan', 'migrate-once'].includes(guard))
assert.match(sql, /alter table public\.job_applications/i)
assert.match(sql, /cv_storage_path text/i)
assert.match(sql, /cv_file_name text/i)
assert.match(sql, /cv_mime_type text/i)
assert.match(sql, /cv_size_bytes integer/i)
assert.match(sql, /job_applications_cv_metadata_check/i)
assert.match(sql, /cv_mime_type = 'application\/pdf'/i)
assert.match(sql, /cv_size_bytes between 1 and 10485760/i)
assert.doesNotMatch(sql, /drop table/i)
assert.doesNotMatch(sql, /drop column/i)
assert.doesNotMatch(sql, /delete from/i)
assert.doesNotMatch(sql, /truncate/i)

assert.match(script, /310356785722/)
assert.match(script, /JOB_APPLICATION_CV_MIGRATION_EXPECTED_SHA/)
assert.match(script, /plan\|migrate-once/)
assert.match(script, /0025_job_application_cv\.sql/)
assert.match(script, /expected exactly three job application CV statements/i)
assert.match(script, /sea-n-shore-job-application-cv-0025/)
assert.match(script, /begin-transaction/)
assert.match(script, /commit-transaction/)
assert.match(script, /rollback-transaction/)
assert.match(script, /JOB_APPLICATION_CV_MIGRATION_PLAN_ONLY_NO_APPLY/)
assert.match(script, /JOB_APPLICATION_CV_MIGRATION_APPLY_VERIFIED=true/)
assert.match(script, /JOB_APPLICATION_CV_MIGRATION_ALREADY_APPLIED=true/)
assert.match(script, /git ls-remote origin refs\/heads\/feat\/aws-native-phase-0-1/)
assert.doesNotMatch(script, /992382634586/)

assert.match(workflow, /Wait for exact-head AWS Infrastructure CI/)
assert.match(workflow, /Guard migration against a moved branch/)
assert.match(workflow, /environment:\s*staging/)
assert.match(workflow, /JOB_APPLICATION_CV_MIGRATION_EXPECTED_SHA/)
assert.match(workflow, /bash scripts\/aws\/job-application-cv-migration\.sh/)

console.log('JOB_APPLICATION_CV_MIGRATION_CONTRACT_VERIFIED=true')
