import assert from 'node:assert/strict'
import fs from 'node:fs'

const sql = fs.readFileSync('infra/aws/database/migrations/0032_membership_access_foundation.sql', 'utf8')
const completionSql = fs.readFileSync('infra/aws/database/migrations/0033_membership_experience_completion.sql', 'utf8')
const script = fs.readFileSync('scripts/aws/membership-access-migration.sh', 'utf8')
const guard = fs.readFileSync('scripts/aws/membership-access-migration-action.txt', 'utf8').trim()
const workflow = fs.readFileSync('.github/workflows/aws-membership-access-migration.yml', 'utf8')

assert.ok(['plan', 'migrate-once'].includes(guard))
assert.match(sql, /add column if not exists persona text/i)
assert.match(sql, /create table if not exists public\.account_subscriptions/i)
assert.match(sql, /create table if not exists public\.feature_verifications/i)
assert.match(sql, /create table if not exists public\.entitlement_grants/i)
assert.match(sql, /create table if not exists public\.legacy_organization_conversions/i)
assert.match(sql, /legacy_migration/i)
assert.doesNotMatch(sql, /drop table/i)
assert.doesNotMatch(sql, /drop column/i)
assert.doesNotMatch(sql, /truncate/i)
assert.doesNotMatch(sql, /delete from/i)

assert.match(script, /310356785722/)
assert.match(script, /MEMBERSHIP_ACCESS_MIGRATION_EXPECTED_SHA/)
assert.match(script, /plan\|migrate-once/)
assert.match(script, /0032_membership_access_foundation\.sql/)
assert.match(script, /0033_membership_experience_completion\.sql/)
assert.match(script, /MEMBERSHIP_ACCESS_COMPLETION_SHAPE_BEFORE/)
assert.match(script, /MEMBERSHIP_ACCESS_COMPLETION_PLAN_VERIFIED=true/)
assert.match(script, /MEMBERSHIP_ACCESS_COMPLETION_APPLY_VERIFIED=true/)
assert.match(script, /MEMBERSHIP_ACCESS_COMPLETION_APPLY_VERIFIED=true"\n+echo "MEMBERSHIP_ACCESS_MIGRATION_APPLY_VERIFIED=true/)
assert.match(script, /sea-n-shore-membership-access-0033/)
assert.match(script, /sea-n-shore-membership-access-0032/)
assert.ok(script.includes("r'create\\s+(unique\\s+)?index\\s+if\\s+not\\s+exists\\s+[a-z0-9_]+\\s+on\\s+public\\."))
assert.ok(script.includes("alter\\s+table\\s+public\\.(profiles|events|learning_courses|feature_verifications|company_access_requests)\\b|'"))
assert.ok(script.includes("r'update\\s+public\\.(profiles|learning_courses|feature_verifications)\\b|'"))
assert.match(script, /begin-transaction/)
assert.match(script, /commit-transaction/)
assert.match(script, /rollback-transaction/)
assert.match(script, /MEMBERSHIP_ACCESS_MIGRATION_PLAN_ONLY_NO_APPLY/)
assert.match(script, /MEMBERSHIP_ACCESS_MIGRATION_APPLY_VERIFIED=true/)
assert.match(script, /MEMBERSHIP_ACCESS_MIGRATION_ALREADY_APPLIED=true/)
assert.match(script, /legacy_organization_conversions/)
assert.match(script, /COMPLETE="5\/5\/4"/)
assert.match(script, /git ls-remote origin refs\/heads\/feat\/aws-native-phase-0-1/)

assert.match(workflow, /Wait for exact-head AWS Infrastructure CI/)
assert.match(workflow, /Guard migration against a moved branch/)
assert.match(workflow, /environment:\s*staging/)
assert.match(workflow, /MEMBERSHIP_ACCESS_MIGRATION_EXPECTED_SHA/)
assert.match(workflow, /0033_membership_experience_completion\.sql/)
assert.match(workflow, /bash scripts\/aws\/membership-access-migration\.sh/)

assert.match(completionSql, /create table if not exists public\.organization_follows/i)
assert.match(completionSql, /company_access_requests_type_check/i)
assert.match(completionSql, /role_access/i)
assert.match(completionSql, /\('creator_pro', 'job\.manage_applicants'\)/i)
assert.match(completionSql, /\('creator_pro', 'event\.manage_attendees'\)/i)
assert.match(completionSql, /\('creator_pro', 'course\.manage_students'\)/i)
assert.match(completionSql, /Preserve existing verified organization applicant-management access/i)
assert.match(completionSql, /Preserve existing active trainer learner-management access/i)
assert.match(completionSql, /Preserve existing event-host attendee-management access/i)

console.log('MEMBERSHIP_ACCESS_MIGRATION_CONTRACT_VERIFIED=true')
