import assert from 'node:assert/strict'
import fs from 'node:fs'

const sql = fs.readFileSync('infra/aws/database/migrations/0024_messaging_rich_media.sql', 'utf8')
const script = fs.readFileSync('scripts/aws/messaging-rich-migration.sh', 'utf8')
const guard = fs.readFileSync('scripts/aws/messaging-rich-migration-action.txt', 'utf8').trim()
const workflow = fs.readFileSync('.github/workflows/aws-messaging-rich-migration.yml', 'utf8')

assert.ok(['plan', 'migrate-once'].includes(guard))
assert.match(sql, /add column reply_to_message_id uuid/i)
assert.match(sql, /attachment_storage_path text/i)
assert.match(sql, /create table public\.message_reactions/i)
assert.match(sql, /messages_reply_to_message_fk/i)
assert.match(sql, /messages_attachment_check/i)
assert.match(sql, /deleted_at is not null or char_length\(body\) >= 1/i)
assert.doesNotMatch(sql, /drop table/i)
assert.doesNotMatch(sql, /drop column/i)
assert.doesNotMatch(sql, /delete from/i)
assert.doesNotMatch(sql, /truncate/i)

assert.match(script, /310356785722/)
assert.match(script, /MESSAGING_RICH_MIGRATION_EXPECTED_SHA/)
assert.match(script, /plan\|migrate-once/)
assert.match(script, /0024_messaging_rich_media\.sql/)
assert.match(script, /expected exactly four rich messaging statements/i)
assert.match(script, /sea-n-shore-messaging-rich-0024/)
assert.match(script, /begin-transaction/)
assert.match(script, /commit-transaction/)
assert.match(script, /rollback-transaction/)
assert.match(script, /MESSAGING_RICH_MIGRATION_PLAN_ONLY_NO_APPLY/)
assert.match(script, /MESSAGING_RICH_MIGRATION_APPLY_VERIFIED=true/)
assert.match(script, /MESSAGING_RICH_MIGRATION_ALREADY_APPLIED=true/)
assert.match(script, /git ls-remote origin refs\/heads\/feat\/aws-native-phase-0-1/)
assert.doesNotMatch(script, /992382634586/)

assert.match(workflow, /Wait for exact-head AWS Infrastructure CI/)
assert.match(workflow, /Guard migration against a moved branch/)
assert.match(workflow, /environment:\s*staging/)
assert.match(workflow, /MESSAGING_RICH_MIGRATION_EXPECTED_SHA/)
assert.match(workflow, /bash scripts\/aws\/messaging-rich-migration\.sh/)

console.log('MESSAGING_RICH_MIGRATION_CONTRACT_VERIFIED=true')
