import assert from 'node:assert/strict'
import fs from 'node:fs'

const sql = fs.readFileSync('infra/aws/database/migrations/0027_post_rich_media.sql', 'utf8')
const script = fs.readFileSync('scripts/aws/post-rich-media-migration.sh', 'utf8')
const guard = fs.readFileSync('scripts/aws/post-rich-media-migration-action.txt', 'utf8').trim()
const workflow = fs.readFileSync('.github/workflows/aws-post-rich-media-migration.yml', 'utf8')

assert.ok(['plan', 'migrate-once'].includes(guard))
assert.match(sql, /alter table public\.post_media[\s\S]*add column if not exists position smallint/i)
assert.match(sql, /add column if not exists file_name text/i)
assert.match(sql, /add column if not exists page_count smallint/i)
assert.match(sql, /drop constraint if exists post_media_post_id_key/i)
assert.match(sql, /drop constraint if exists post_media_mime_check/i)
assert.match(sql, /application\/pdf/i)
assert.match(sql, /page_count between 1 and 50/i)
assert.match(sql, /position between 0 and 9/i)
assert.match(sql, /unique \(post_id, position\)/i)
assert.doesNotMatch(sql, /drop table/i)
assert.doesNotMatch(sql, /drop column/i)
assert.doesNotMatch(sql, /delete from/i)
assert.doesNotMatch(sql, /truncate/i)

assert.match(script, /310356785722/)
assert.match(script, /POST_RICH_MEDIA_MIGRATION_EXPECTED_SHA/)
assert.match(script, /plan\|migrate-once/)
assert.match(script, /0027_post_rich_media\.sql/)
assert.match(script, /expected exactly eight post rich media statements/i)
assert.match(script, /sea-n-shore-post-rich-media-0027/)
assert.match(script, /begin-transaction/)
assert.match(script, /commit-transaction/)
assert.match(script, /rollback-transaction/)
assert.match(script, /POST_RICH_MEDIA_MIGRATION_PLAN_ONLY_NO_APPLY/)
assert.match(script, /POST_RICH_MEDIA_MIGRATION_APPLY_VERIFIED=true/)
assert.match(script, /POST_RICH_MEDIA_MIGRATION_ALREADY_APPLIED=true/)
assert.match(script, /git ls-remote origin refs\/heads\/feat\/aws-native-phase-0-1/)
assert.doesNotMatch(script, /992382634586/)

assert.match(workflow, /Wait for exact-head AWS Infrastructure CI/)
assert.match(workflow, /Guard migration against a moved branch/)
assert.match(workflow, /environment:\s*staging/)
assert.match(workflow, /POST_RICH_MEDIA_MIGRATION_EXPECTED_SHA/)
assert.match(workflow, /bash scripts\/aws\/post-rich-media-migration\.sh/)

console.log('POST_RICH_MEDIA_MIGRATION_CONTRACT_VERIFIED=true')
