import { withTransaction as databaseTransaction } from '@/lib/db/client'
import {
  createOnboardingRepositoryForClient,
  type OnboardingRepository,
} from './onboarding-repository'
import type { OnboardingInput } from './schemas'

export type ProfileEditRepository = Pick<
  OnboardingRepository,
  | 'lockCompletedProfile'
  | 'updateCompletedProfile'
  | 'upsertMaritimeProfile'
  | 'upsertActivationMaritimeProfile'
  | 'upsertCurrentOrganization'
  | 'updateRank'
  | 'deleteMaritimeProfile'
  | 'replaceSkills'
>

type ProfileEditTransaction = <T>(fn: (repository: ProfileEditRepository) => Promise<T>) => Promise<T>

function serviceError(code: string): never {
  throw new Error(code)
}

export function createProfileEditService(input: { withTransaction: ProfileEditTransaction }) {
  async function updateProfile(
    actorId: string,
    data: OnboardingInput,
    supportsCurrentCompany = data.profileType === 'seafarer' || data.profileType === 'maritime_professional',
    options: { currentCompanySubmitted?: boolean; rankSubmitted?: boolean } = {},
  ) {
    return input.withTransaction(async (repository) => {
      const current = await repository.lockCompletedProfile(actorId)
      if (!current) serviceError('profile_edit_unavailable')

      const usernameChanged = current.slug !== data.slug
      // A handle Sea N Shore generated at onboarding can be replaced once without using a change.
      if (usernameChanged && !current.usernameAutoGenerated && current.usernameChangeCount >= 2) {
        serviceError('username_change_limit')
      }

      if (!await repository.updateCompletedProfile(actorId, data)) {
        serviceError('profile_edit_unavailable')
      }

      if (data.profileType === 'seafarer') {
        await repository.upsertMaritimeProfile(actorId, data)
      } else if (supportsCurrentCompany && (options.currentCompanySubmitted || data.currentCompany !== undefined)) {
        // Only the organization changes here, so legacy details such as rank are kept.
        await repository.upsertCurrentOrganization(actorId, data.currentCompany, data.currentCompanyId)
      }
      if (data.profileType !== 'seafarer' && options.rankSubmitted) {
        // Round 10: a rank saved by an earlier profile is shown on posts, so the member can edit or clear it.
        await repository.updateRank(actorId, data.rank)
      }

      await repository.replaceSkills(actorId, data.skills)
      return true
    })
  }

  return { updateProfile }
}

const productionService = createProfileEditService({
  withTransaction: (fn) => databaseTransaction((client) => fn(createOnboardingRepositoryForClient(client))),
})

export const updateProfileWithAurora = productionService.updateProfile
